/**
 * 24 fictional sponsors for the NIL-style deal marketplace. All brands are
 * invented — no real companies. Tiers scale from local promotions to national
 * ambassadorships, with escalating requirements and payouts.
 */

import type { Sponsor } from "@/game-engine/types";

export const SPONSORS: Sponsor[] = [
  // --- Local (tier: local) ---
  {
    id: "sp-pancake",
    company: "Sunrise Stack Diner",
    tier: "local",
    category: "Local Restaurant",
    basePayment: 1200,
    durationWeeks: 6,
    weeklyObligation: "Weekend appearance",
    reqReputation: 8,
    reqFollowing: 200,
    reqGpa: 2.0,
    performanceBonus: 200,
    conflictClause: "No competing diners",
    personalityFit: ["Laid Back", "Coachable"],
  },
  {
    id: "sp-tacos",
    company: "El Camino Tacos",
    tier: "local",
    category: "Local Restaurant",
    basePayment: 1500,
    durationWeeks: 6,
    weeklyObligation: "One social post",
    reqReputation: 10,
    reqFollowing: 500,
    reqGpa: 2.0,
    performanceBonus: 250,
    conflictClause: "No competing food trucks",
    personalityFit: ["Media Darling"],
  },
  {
    id: "sp-barber",
    company: "Fade Factory Barbers",
    tier: "local",
    category: "Local Service",
    basePayment: 900,
    durationWeeks: 8,
    weeklyObligation: "Wear branded gear",
    reqReputation: 6,
    reqFollowing: 150,
    reqGpa: 2.0,
    performanceBonus: 150,
    conflictClause: "None",
    personalityFit: ["Fiery Competitor"],
  },
  {
    id: "sp-smoothie",
    company: "GreenBlend Smoothies",
    tier: "local",
    category: "Local Restaurant",
    basePayment: 1400,
    durationWeeks: 5,
    weeklyObligation: "Weekly check-in post",
    reqReputation: 12,
    reqFollowing: 800,
    reqGpa: 2.3,
    performanceBonus: 200,
    conflictClause: "No competing juice bars",
    personalityFit: ["Coachable"],
  },

  // --- Apparel ---
  {
    id: "sp-apex",
    company: "Apex Athletic",
    tier: "apparel",
    category: "Athletic Apparel",
    basePayment: 6000,
    durationWeeks: 10,
    weeklyObligation: "Wear cleats on game day",
    reqReputation: 35,
    reqFollowing: 4000,
    reqGpa: 2.3,
    performanceBonus: 800,
    conflictClause: "No competing apparel brands",
    personalityFit: ["Fiery Competitor", "Natural Leader"],
  },
  {
    id: "sp-stridewear",
    company: "Stridewear",
    tier: "apparel",
    category: "Athletic Apparel",
    basePayment: 5200,
    durationWeeks: 12,
    weeklyObligation: "Two posts per month",
    reqReputation: 30,
    reqFollowing: 3000,
    reqGpa: 2.3,
    performanceBonus: 700,
    conflictClause: "No competing shoe brands",
    personalityFit: ["Media Darling"],
  },
  {
    id: "sp-gridiron-co",
    company: "Gridiron & Co.",
    tier: "apparel",
    category: "Athletic Apparel",
    basePayment: 4800,
    durationWeeks: 10,
    weeklyObligation: "Branded warmups",
    reqReputation: 28,
    reqFollowing: 2500,
    reqGpa: 2.0,
    performanceBonus: 600,
    conflictClause: "No competing gear",
    personalityFit: ["Coachable"],
  },

  // --- Gaming ---
  {
    id: "sp-nitro",
    company: "Nitro Peripherals",
    tier: "gaming",
    category: "Gaming Accessory",
    basePayment: 4500,
    durationWeeks: 8,
    weeklyObligation: "Stream 1 hr/week",
    reqReputation: 25,
    reqFollowing: 6000,
    reqGpa: 2.0,
    performanceBonus: 500,
    conflictClause: "No competing gaming brands",
    personalityFit: ["Laid Back", "Media Darling"],
  },
  {
    id: "sp-pixelforge",
    company: "PixelForge",
    tier: "gaming",
    category: "Gaming Accessory",
    basePayment: 5000,
    durationWeeks: 8,
    weeklyObligation: "Feature product in stream",
    reqReputation: 30,
    reqFollowing: 9000,
    reqGpa: 2.0,
    performanceBonus: 600,
    conflictClause: "No competing peripherals",
    personalityFit: ["Lone Wolf"],
  },

  // --- Drink ---
  {
    id: "sp-rally",
    company: "Rally Energy",
    tier: "drink",
    category: "Sports Drink",
    basePayment: 8000,
    durationWeeks: 10,
    weeklyObligation: "Sideline branding",
    reqReputation: 42,
    reqFollowing: 8000,
    reqGpa: 2.5,
    performanceBonus: 1000,
    conflictClause: "No competing energy drinks",
    personalityFit: ["Fiery Competitor"],
  },
  {
    id: "sp-hydro",
    company: "HydroSurge",
    tier: "drink",
    category: "Sports Drink",
    basePayment: 7200,
    durationWeeks: 12,
    weeklyObligation: "Post-workout content",
    reqReputation: 38,
    reqFollowing: 7000,
    reqGpa: 2.5,
    performanceBonus: 900,
    conflictClause: "No competing hydration brands",
    personalityFit: ["Natural Leader"],
  },
  {
    id: "sp-coldbrew",
    company: "Midnight Cold Brew",
    tier: "drink",
    category: "Beverage",
    basePayment: 3800,
    durationWeeks: 8,
    weeklyObligation: "Morning routine post",
    reqReputation: 22,
    reqFollowing: 3500,
    reqGpa: 2.3,
    performanceBonus: 400,
    conflictClause: "None",
    personalityFit: ["Laid Back"],
  },

  // --- Auto ---
  {
    id: "sp-summit-motors",
    company: "Summit Motors",
    tier: "auto",
    category: "Car Dealership",
    basePayment: 9000,
    durationWeeks: 12,
    weeklyObligation: "Monthly dealership visit",
    reqReputation: 45,
    reqFollowing: 6000,
    reqGpa: 2.5,
    performanceBonus: 1200,
    conflictClause: "No competing dealerships",
    personalityFit: ["Natural Leader", "Media Darling"],
  },
  {
    id: "sp-ridgeline",
    company: "Ridgeline Auto Group",
    tier: "auto",
    category: "Car Dealership",
    basePayment: 8500,
    durationWeeks: 10,
    weeklyObligation: "Commercial cameo",
    reqReputation: 48,
    reqFollowing: 7500,
    reqGpa: 2.5,
    performanceBonus: 1100,
    conflictClause: "No competing auto brands",
    personalityFit: ["Fiery Competitor"],
  },

  // --- Community ---
  {
    id: "sp-unite",
    company: "UniteWorks Foundation",
    tier: "community",
    category: "Community Campaign",
    basePayment: 3000,
    durationWeeks: 8,
    weeklyObligation: "Volunteer 2 hrs/week",
    reqReputation: 20,
    reqFollowing: 2000,
    reqGpa: 2.8,
    performanceBonus: 300,
    conflictClause: "Must maintain clean record",
    personalityFit: ["Natural Leader", "Coachable"],
  },
  {
    id: "sp-readfirst",
    company: "ReadFirst Literacy",
    tier: "community",
    category: "Community Campaign",
    basePayment: 2600,
    durationWeeks: 10,
    weeklyObligation: "School reading visit",
    reqReputation: 18,
    reqFollowing: 1500,
    reqGpa: 3.0,
    performanceBonus: 250,
    conflictClause: "Academic standing required",
    personalityFit: ["Coachable"],
  },

  // --- Social ---
  {
    id: "sp-loop",
    company: "Loop Social",
    tier: "social",
    category: "Social Platform",
    basePayment: 5500,
    durationWeeks: 8,
    weeklyObligation: "3 posts/week",
    reqReputation: 30,
    reqFollowing: 15000,
    reqGpa: 2.0,
    performanceBonus: 700,
    conflictClause: "No competing platforms",
    personalityFit: ["Media Darling"],
  },
  {
    id: "sp-clipreel",
    company: "ClipReel",
    tier: "social",
    category: "Social Platform",
    basePayment: 6200,
    durationWeeks: 10,
    weeklyObligation: "Weekly highlight reel",
    reqReputation: 34,
    reqFollowing: 20000,
    reqGpa: 2.0,
    performanceBonus: 800,
    conflictClause: "Exclusive content window",
    personalityFit: ["Media Darling", "Lone Wolf"],
  },

  // --- Regional ---
  {
    id: "sp-frostbank",
    company: "Frostbank Financial",
    tier: "regional",
    category: "Regional Commercial",
    basePayment: 12000,
    durationWeeks: 12,
    weeklyObligation: "Quarterly shoot",
    reqReputation: 55,
    reqFollowing: 25000,
    reqGpa: 2.8,
    performanceBonus: 1500,
    conflictClause: "No competing banks",
    personalityFit: ["Natural Leader"],
  },
  {
    id: "sp-heartland-air",
    company: "Heartland Airlines",
    tier: "regional",
    category: "Regional Commercial",
    basePayment: 11000,
    durationWeeks: 10,
    weeklyObligation: "Travel content",
    reqReputation: 52,
    reqFollowing: 22000,
    reqGpa: 2.5,
    performanceBonus: 1400,
    conflictClause: "No competing airlines",
    personalityFit: ["Media Darling"],
  },
  {
    id: "sp-peak-outdoors",
    company: "Peak Outdoors",
    tier: "regional",
    category: "Regional Retail",
    basePayment: 9500,
    durationWeeks: 12,
    weeklyObligation: "Seasonal campaign",
    reqReputation: 48,
    reqFollowing: 18000,
    reqGpa: 2.5,
    performanceBonus: 1200,
    conflictClause: "No competing outfitters",
    personalityFit: ["Laid Back", "Fiery Competitor"],
  },

  // --- National ---
  {
    id: "sp-velocity",
    company: "Velocity Global",
    tier: "national",
    category: "National Ambassador",
    basePayment: 30000,
    durationWeeks: 16,
    weeklyObligation: "National campaign duties",
    reqReputation: 72,
    reqFollowing: 60000,
    reqGpa: 2.8,
    performanceBonus: 4000,
    conflictClause: "Exclusive category rights",
    personalityFit: ["Natural Leader", "Media Darling"],
  },
  {
    id: "sp-monarch",
    company: "Monarch Athletics",
    tier: "national",
    category: "National Ambassador",
    basePayment: 26000,
    durationWeeks: 16,
    weeklyObligation: "Signature product line",
    reqReputation: 68,
    reqFollowing: 50000,
    reqGpa: 2.5,
    performanceBonus: 3500,
    conflictClause: "No competing global brands",
    personalityFit: ["Fiery Competitor"],
  },
  {
    id: "sp-astra",
    company: "Astra Devices",
    tier: "national",
    category: "National Ambassador",
    basePayment: 28000,
    durationWeeks: 14,
    weeklyObligation: "Product launch events",
    reqReputation: 70,
    reqFollowing: 55000,
    reqGpa: 3.0,
    performanceBonus: 3800,
    conflictClause: "Exclusive tech category",
    personalityFit: ["Media Darling", "Natural Leader"],
  },
];

export function getSponsor(id: string): Sponsor | undefined {
  return SPONSORS.find((s) => s.id === id);
}

export const SPONSOR_TIER_LABELS: Record<Sponsor["tier"], string> = {
  local: "Local",
  apparel: "Apparel",
  gaming: "Gaming",
  drink: "Beverage",
  auto: "Automotive",
  community: "Community",
  social: "Social",
  regional: "Regional",
  national: "National",
};
